# Generated by Django 5.2.4 on 2025-08-20 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_userinfos_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='userr',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userinfos',
            old_name='userr',
            new_name='user',
        ),
    ]
