# Generated by Django 5.2.4 on 2025-08-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_messages_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='user',
            field=models.CharField(max_length=150),
        ),
    ]
